project_name: chopdoc

version: 2
before:
  hooks:
    - go mod tidy

builds:
  - id: "chopdoc"
    binary: "chopdoc"
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -tags=netgo
    ldflags:
      # Omit the symbol table and debug information.
      - "-s"
      # Omit the DWARF symbol table.
      - "-w"
      - "-X main.Version={{ .Version }}"
      - "-X main.Commit={{ .ShortCommit }}"
      - "-X main.CommitDate={{ .CommitDate }}"
      - "-X main.TreeState={{ .GitTreeState }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: "./chopdoc.go"

archives:
  - format: "binary"
    id: "binary"
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

brews:
  - name: "chopdoc"
    ids:
      - "binary"
    repository:
      owner: "mirpo"
      name: "homebrew-tools"
      branch: "main"
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: mirpo
      email: 7105861+mirpo@users.noreply.github.com
    homepage: "https://github.com/mirpo/chopdoc"
    description: "A tool to split documents into chunks for RAG and LLM applications"
    license: "MIT"
