project_name: chopdoc
version: 2
before:
  hooks:
    - go mod tidy

builds:
  - env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    flags:
      - -trimpath
      - -tags=netgo
    ldflags:
      - "-X main.Version={{ .Version }}"
      - "-X main.Commit={{ .ShortCommit }}"
      - "-X main.CommitDate={{ .CommitDate }}"
      - "-X main.TreeState={{ .GitTreeState }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

checksum:
  name_template: "checksums.txt"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

gomod:
  proxy: false

brews:
  - repository:
      owner: mirpo
      name: homebrew-tools
      token: "{{ .Env.GITHUB_TOKEN }}"
    commit_author:
      name: mirpo
      email: 7105861+mirpo@users.noreply.github.com
    homepage: "https://github.com/mirpo/chopdoc"
    description: "A tool to split documents into chunks for RAG and LLM applications"
